---
kind: Service
apiVersion: v1
metadata:
  name: torchserve
  labels:
    app: torchserve
spec:
  ports:
  - name: preds
    port: 8080
    targetPort: ts
  - name: mdl
    port: 8081
    targetPort: ts-management
  - name: metrics
    port: 8082
    targetPort: ts-metrics
  type: LoadBalancer
  selector:
    app: torchserve
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: torchserve
  labels:
    app: torchserve
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: torchserve
  template:
    metadata:
      labels:
        app: torchserve
    spec:
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolume.name }}
      containers:
      - name: torchserve
        image: {{ .Values.torchserve_image }}
        args: ["torchserve", "--start",  "--models", "all", "--model-store", "/home/model-server/shared/model-store/", "--ts-config", "/home/model-server/shared/config/config.properties"]
        ports:
        - name: ts
          containerPort: 8080
        - name: ts-management
          containerPort: 8081
        - name: ts-metrics
          containerPort: 8082
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: {{ .Values.torchserve.pvd_mount }}
            name: persistent-storage
        resources:
          limits:
            cpu: {{ .Values.torchserve.n_cpu }}
            memory: {{ .Values.torchserve.memory_limit }}
            nvidia.com/gpu: {{ .Values.torchserve.n_gpu }}
