apiVersion: v1
kind: Pod
metadata:
  name: model-store-pod
spec:
  containers:
    - name: model-store
      image: ubuntu
      command: [ "sleep" ]
      args: [ "infinity" ]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: pod-volume
          mountPath: "/pv"
  volumes:
  - name: pod-volume
    persistentVolumeClaim:
      claimName: model-store-claim